leftnav:
- identifier: 89b22769-e5d0-4a18-9eeb-549eb9970eef
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: aa3d9f80-b60a-49e9-a38b-56e6d8291a35
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: d2c09e5a-d51d-4ca4-bf08-d08d496f311d
  name: 'Week 1: What are we trying to do here?'
  pageRef: /pages/week-1-the-challenge
  weight: 30
- identifier: 7787d088-08d1-4e8c-beff-017fb0022ce5
  name: 'Week 2: Data are wasted, lost, and under-used'
  pageRef: /pages/week-1-response-paper
  weight: 40
- identifier: 27e54345-dff3-41c7-bbf8-9b38f4e2bfea
  name: 'Week 9: Researchers are incentivized to be first, not right'
  pageRef: /pages/week-9-challenge-researchers-are-incentivized-to-be-first-not-right
  weight: 50
- identifier: 6724d0d9-0dce-4061-bd31-6e1d3a943de7
  name: Week 1 Response Paper
  pageRef: /pages/week-1-response-paper2
  parent: d2c09e5a-d51d-4ca4-bf08-d08d496f311d
  weight: 10
- identifier: 6f6af34a-693e-4fbe-840c-e2b2a24644a0
  name: 'Week 2 Tool: FAIR data sharing'
  pageRef: /pages/week-2-the-tool
  parent: 7787d088-08d1-4e8c-beff-017fb0022ce5
  weight: 10
- identifier: 9b792c82-ab5b-4cf3-9c73-1454013308d1
  name: Week 2 Response Paper
  pageRef: /pages/week-2-response-paper
  parent: 7787d088-08d1-4e8c-beff-017fb0022ce5
  weight: 20
